name: T2POI-CI

on:
  push:
    branches: [ OHT2.POI ]
    paths: 'apis/poi/**'
  pull_request:
    branches: [ master ]
    paths: 'apis/poi/**' 
      
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
      
  - name: Setup .NET Core SDK
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version: '3.1.202'
 # - name: Add code Coverage Tools
 #   working-directory: apis/poi/tests/UnitTests 
 #   run: dotnet add add package coverlet.msbuild   
     
  - name: Install dependencies
    run: dotnet restore apis/poi/web/*.csproj
    
  - name: .NET Build Web 
    run: dotnet build --configuration Release --no-restore apis/poi/web/*.csproj
    
  - name: dotnet build Unit Tests
    run: dotnet build --configuration Release apis/poi/tests/UnitTests/UnitTests.csproj
    
  - name: dotnet Unit Test
    run: dotnet test apis/poi/tests/UnitTests/UnitTests.csproj
    
  - name: .NET Test 
    run: dotnet test --no-restore --verbosity normal apis/poi/tests/UnitTests  /p:CollectCoverage=true /p:CoverletOutput=lcov/  /p:CoverletOutputFormat=lcov
        
  - name: Coveralls
    uses: coverallsapp/github-action@master
    with:
      github-token: S{{ secrets.GITHUB_TOKEN }}
      path-to-lcov: apis/poi/tests/UnitTests/lcov/coverage.info
      base-path: apis/poi
      flag-name: Unit




