# This workflow will build and push a node.js application to an Azure Web App when a release is created.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/azure/app-service/app-service-plan-manage#create-an-app-service-plan
#
#
#
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
on:
  push:
    branches: [ OHT2.POI ]
    paths: 'apis/poi/**'
  pull_request:
    branches: [ master ]
    paths: 'apis/poi/**'
  
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
name: Build and Push to ACR
jobs:
  build-and-deploy:
    # Starts jobs and sets the type of runner (ubuntu-latest) they will run on
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
   # Use docker login
        - name: 'Docker Login'
          uses: azure/docker-login@v1
          with:
           login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
           username: ${{ secrets.REGISTRY_USERNAME }}
           password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -f apis/poi/web/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}api-poi:${{ github.sha }} .
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}api-poi:${{ github.sha }}
